# docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
